version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.31.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.0.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.22.0
